name: Security-Scan-dotNET

trigger: none

pr:
  branches:
    include:
      - main
      - master 

resources:
  repositories:
    - repository: pipeline-templates
      type: github
      name: gcxchange-gcechange/security-pipeline
      ref: refs/heads/master
      endpoint: 'GCExchange (3)'

variables:
  NVD_API_KEY: $(NVD_API_KEY)

pool:
  vmImage: ubuntu-latest

extends:
  template: backend-template.yml@pipeline-templates
  parameters:
    nvdApiKey: $(NVD_API_KEY)
